# Default values for tfc-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  name: "terraform-cloud-agent"
  image: "hashicorp/tfc-agent"
  replicacount: 1
  prefix: "tfcagent"
  version: "latest"
  log_level: "error" # options: TRACE, DEBUG, INFO, WARN or ERROR
  disable_update: "true"
  tfc_address: "https://app.terraform.io"
  tfcAgentToken: ""
namespace:
  create: true
  name: "tfc-agent"

role:
  name: "terraform-cloud-agent"
  rules:
    apiGroups: ["", "apps", "autoscaling", "batch", "extensions", "policy", "rbac.authorization.k8s.io"]
    resources: ["componentstatuses", "configmaps", "daemonsets", "deployments", "events", "endpoints", "horizontalpodautoscalers", "ingress", "jobs", "limitranges", "namespaces", "nodes", "pods", "persistentvolumes", "persistentvolumeclaims", "resourcequotas", "replicasets", "replicationcontrollers", "serviceaccounts", "services"]
    verbs: ["*"]

serviceAccount:
  name: ""

clusterrolebinding:
  name: "terraform-cloud-agent"
