apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterrolebinding.name }}
subjects:
- kind: ServiceAccount
  name: 
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io