apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
{{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
rules:
- apiGroups: {{ .Values.role.rules.apiGroups }}
  resources: {{ .Values.role.rules.resources }}
  verbs: {{ .Values.role.rules.verbs }}
