{{ if not (lookup "v1" "Secret" .Values.namespace.name .Values.serviceAccount.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
{{ end }}
