{{ if not (lookup "v1" "ServiceAccount" .Values.namespace.name .Values.serviceAccount.name ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": "pre-install"
{{ end }}