apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tfcAgentToken.name }}
  namespace: {{ .Values.namespace.name }}
data:
  token: {{ default ""  .Values.tfcAgentToken.data.token | b64enc | quote }}
