{{ if not (lookup "v1" "Secret" .Values.namespace.name .Values.tfcAgentToken.name ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tfcAgentToken.name }}
  namespace: {{ .Values.namespace.name }}
data:
  token: {{ default ""  .Values.tfcAgentToken.data.token | b64enc | quote }}
{{ end }}